contact/urls.py
from django.template.context_processors import static
from django.urls import path

from myfirstcontactapp import settings
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'contact'

urlpatterns = [
                  path('', views.contact_list, name='contact_list'),
                  path('person/<int:pk>', views.contact_detail, name='contact_detail'),
                  path('person/new', views.contact_new, name='contact_new'),
                  path('person/<int:pk>/edit', views.contact_edit, name='contact_edit'),
                  path('person/<int:pk>/delete', views.contact_delete, name='contact_delete'),
                  path('', views.contact_search, name='contact_list')

              ] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone

objects = models.Manager()
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage


class Person(models.Model) :
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=250)
    phone = models.CharField(max_length=250)
    address = models.CharField(max_length=250, default='Singapore')
    createddate = models.DateTimeField(auto_now_add=True)
    modifieddate = models.DateTimeField(auto_now=True)
    #profilepic = models.ImageField()
    #profilepic = models.ImageField(upload_to='media' , blank=True)




    def publish(self) :
        self.published_date = timezone.now()
        self.save()

    def full_name(self) :
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self) :
        return self.full_name()

contact/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person

        fields = ('first_name', 'last_name', 'email', 'phone', 'address')

contact/views.py
from .forms import PersonForm


def contact_list(request):
    persons = Person.objects.all().order_by('first_name')
    if request.GET.get('search') :
        search = request.GET.get('search')
        persons = Person.objects.filter(first_name__contains=search)
    return render(request, 'contact/contact_list.html', {'persons': persons, 'count': persons.count()})





def contact_detail(request, pk) :
    person = get_object_or_404(Person, pk=pk)
    return render(request, 'contact/contact_detail.html', {'person' : person})


def contact_new(request) :
    if request.method == 'POST' :
        form = PersonForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('/')
    else:
        form = PersonForm()
    return render(request, 'contact/contact_edit.html', {'form': form})


def contact_edit(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('/person/' + str(person.pk))
    else:
        form = PersonForm(instance=person)
    return render(request, 'contact/contact_edit.html', {'form': form})


def contact_delete(request, pk) :
    person = get_object_or_404(Person, pk=pk)
    person.delete()
    return redirect('/')


# def contact_search(request, searchname) :
#    persons = Person.objects.all().order_by('last_name')
# searchname = request.GET.get('search')
# persons = Person.objects.filter(first_name__icontains=searchname)
# p = persons.object.get(first_name__icontains=searchname)
# return render(request, 'contact/search.html', {'persons' : persons, 'count' : persons.count()})


def contact_search(request):
    questions = None
    query = None
    if request.GET.get('search'):
        search = request.GET.get('search')
        questions = Person.objects.filter(first_name__contains=search)

        name = request.GET.get('name')
        query = Person.object.filter(first_name__contains=search)

    return render(request, 'contact/contact_list.html', {
        'questions': questions
    })


from django.shortcuts import render
from .models import Person

contact/templates/contact/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Contact App</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'contact:contact_new' %}" class="float-right"><i class="far fa-plus-square"></i></a>
            <h1><a href="/">CONTACT APP</a></h1>
            <p>There are {{count}} entries in your contact list.</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

contact/templates/contact/contact_detail.html
{% extends 'contact/base.html' %}
{% block content %}
    <div class="card">
      <div class="card-body">
     <p class="card-title">Name-<a href="mailto:{{ person.full_name }}">{{ person.full_name }}</a></p>
        <p class="card-text">Email- <a href="mailto:{{ person.email }}">{{ person.email }}</a></p>
        <p class="card-text">Phone- <a href="tel:{{ person.phone }}">{{ person.phone }}</a></p>
          <p class="card-text">Address- <a href="address:{{ person.address}}">{{ person.address }}</a></p>
          <a href="{% url 'contact:contact_edit' person.id %}"><button class="btn btn-primary">Edit</button></a>
        <a href="{% url 'contact:contact_delete' person.id %}"><button class="btn btn-primary">Delete</button></a>
      </div>
    </div>

{% endblock %}

contact/templates/contact/contact_edit.html
{% extends 'contact/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    {{ form.as_p }}
    </div>
    <input class="btn btn-primary" type="submit" value="Save" />
</form>
{% endblock %}

contact/templates/contact/contact_list.html
{% extends 'contact/base.html' %}
{% block content %}
<form method="GET">
    Search: <input type="text" name="search"><br/>

    <input type="submit" value="Submit" />
</form><br/><br/>



    <div class="card" style="width: 18rem;">

        <ul class="list-group list-group-flush">
            {% for person in persons %}
                <div>
                    <li class="list-group-item"><a href="{% url 'contact:contact_detail' person.id %}">{{ person.full_name }}</a></li>
                </div>
            {% endfor %}

        </ul>
     <ol class="list-group list-group-flush">
            {% for questions in questions %}

                <div>
                    <li class="list-group-item"><a href="{% url 'contact:contact_detail' questions.id%}">{{ questions.full_name}}</a></li>
                </div>
            {% endfor %}
        </ol>
    </div>
    <div class="card" style="width: 18rem;">
        <ol class="list-group list-group-flush">
            {% for questions in questions %}

                <div>
                    <li class="list-group-item"><a href="{% url 'contact:contact_detail'%}">{{ questions.full_name}}</a></li>
                </div>
            {% endfor %}
        </ol>
    </div>




{% endblock %}

contact/templates/contact/contact_search.html
{% extends 'contact/base.html' %}
{% block content %}

    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            {% for questions in questions %}

                <div>
                    <li class="list-group-item"><a href="{% url 'contact:contact_detail' questions.id%}">{{ questions.full_name}}</a></li>
                </div>
            {% endfor %}
        </ul>
    </div>

{% endblock %}